### ISSUE TITLE
problem with recent changes

### ISSUE THREAD

**Issue by lollul** [trekawek/air-quality-info#18]
I've tried to update to current version but facing errors:
```
2019/06/03 10:40:04 [error] 424#424: *23 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/air-quality-info): failed to open stream: Success in /var/www/air-quality-info/boot.php on line 11
PHP message: PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /var/www/air-quality-info/boot.php on line 11" while reading response header from upstream, client: x.x.x.x, server: zlawies.eu, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "xxx.xxx"
```

All I could understand from the above is that it has a problem finding config.php. I then reverted the recent changes in boot.php related to config.php only to reach another error:
```
2019/06/03 10:05:37 [error] 31324#31324: *187497 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Can't load file /lib/di_container.php for class AirQualityInfo\Lib\DiContainer in /var/www/air-quality-info/boot.php:22
Stack trace:
#0 [internal function]: AirQualityInfo\{closure}('AirQualityInfo\\...')
#1 /var/www/air-quality-info/boot.php(27): spl_autoload_call('AirQualityInfo\\...')
#2 /var/www/air-quality-info/index.php(4): require('/var/www/air-qu...')
#3 {main}
  thrown in /var/www/air-quality-info/boot.php on line 22" while reading response header from upstream, client: x.x.x.x, server: zlawies.eu, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "xxx.xxx"
```

I've now rolled back to Mar 23 version and all is fine.
I'm running this on a ubuntu 16.04 OpenVz VPS server. Are there new requirements for PHP or fpm etc?

**Comment by trekawek** [comment]
@lollul - yes, the standalone version is no longer supported. The new docker-compose.yml file should allow to start the service (see [README](https://github.com/trekawek/air-quality-info#setup)), but the data has to be migrated manually.
