### ISSUE TITLE
Blank page on startup

### ISSUE THREAD

**Issue by kyob** [trekawek/air-quality-info#22]
```bash
# docker -v
Docker version 19.03.5, build 633a0ea838

# docker-compose -v
docker-compose version 1.24.1, build 4667896b
```

Docker logs:
```bash
fpm_1         | NOTICE: PHP message: PHP Notice:  Undefined index: spaces in /var/www/html/boot.php on line 38
fpm_1         | NOTICE: PHP message: PHP Notice:  Undefined index: spaces in /var/www/html/boot.php on line 38
fpm_1         | NOTICE: PHP message: PHP Notice:  Undefined index: spaces in /var/www/html/boot.php on line 38
fpm_1         | NOTICE: PHP message: PHP Notice:  Undefined index: spaces in /var/www/html/boot.php on line 38
fpm_1         | NOTICE: PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Missing required client configuration options: 
fpm_1         | region: (string)
fpm_1         |   A "region" configuration value is required for the "s3" service
fpm_1         |   (e.g., "us-west-2"). A list of available public regions and endpoints can be
fpm_1         |   found at http://docs.aws.amazon.com/general/latest/gr/rande.html. in /var/www/html/vendor/aws/aws-sdk-php/src/ClientResolver.php:397
fpm_1         | Stack trace:
fpm_1         | #0 /var/www/html/vendor/aws/aws-sdk-php/src/ClientResolver.php(293): Aws\ClientResolver->throwRequired(Array)
fpm_1         | 172.18.0.2 -  25/Nov/2019:13:14:08 +0000 "GET /index.php" 500
fpm_1         | #1 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClient.php(187): Aws\ClientResolver->resolve(Array, Object(Aws\HandlerList))
fpm_1         | #2 /var/www/html/vendor/aws/aws-sdk-php/src/S3/S3Client.php(283): Aws\AwsClient->__construct(Array)
fpm_1         | #3 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClient.php(429): Aws\S3\S3Client->__construct(Array)
fpm_1         | #4 /var/www/html/vendor/sociallydev/spaces-api/spaces.php(39): Aws\AwsClient::factory(Array)
fpm_1         | #5 /var/www/html/boot.php(38): SpacesConnect->__construct(NULL, NULL, NULL, NULL)
fpm_1         | #6 /var/www/html/ind in /var/www/html/vendor/aws/aws-sdk-php/src/ClientResolver.php on line 397

```

**Comment by kyob** [comment]
Czy do działania potrzebne jest konto na AWS, bo tak wynika z komunikatu, a nie widzę takiej wzmianki stronie https://github.com/trekawek/air-quality-info/blob/master/README.md

**Comment by trekawek** [comment]
The S3 account is required for storing the record archive. In the 72a669555afad9dc16cd980f84c50bbc1b99436b I added S3 simulator, which can be used for the local deployments. It's configured by default in 51bcbefc45014da7f4e1b848767a984f0e35388a.
